### ISSUE TITLE
Characteristics are undocumented

### ISSUE THREAD

**Issue by BurntBrunch** [orlopau/ember-mug#1]
Hi,

I appreciate you starting down on this journey! I got one of these for Christmas and would love to build a small python tool to control it.

However, I'm struggling to understand this repository - it documents the service UUID, sure, but it doesn't actually document which characteristic is which of the interfaces you've found? Can you publish that mapping as well, please?

Thanks!

**Comment by BurntBrunch** [comment]
Nevermind, reader confusion :)

**Comment by Ryamonster10** [comment]
Hello, looking to do a similar thing, I would like to know if you finished yours and if so, what you do to make it work because for the life of me I can't get it to work lol. Thanks. Also: I am not making something physical, rater command-line scripts that run on my computer to make my drink 160 instead of 145 (F). So all I need is to change the temperature. Not anything else but I can't figure out how to do that.

**Comment by pledi** [comment]
I'm also interested in a small tool to control the mug from my computer (or later a better android app haha). 
@BurntBrunch and @Ryamonster10 have you started already ?  We could work on a command line tool with basic functionality

**Comment by orlopau** [comment]
I used nRF Connect (Android) to scan the device's characteristics. 
You can also send data using this app, that's how i found out the dataformats.

**Comment by Ryamonster10** [comment]
> I'm also interested in a small tool to control the mug from my computer (or later a better android app haha).
> @BurntBrunch and @Ryamonster10 have you started already? We could work on a command line tool with basic functionality

I have not started yet but looked into it (how I found this) but yes, we could work on something like that although I don't have any experience interfacing with Bluetooth devices. 
I also wonder if we can use some of the app's existing code, although I am not sure how you would go about decompiling an app like that, that is only available via google play store.

**Comment by Ryamonster10** [comment]
> I used nRF Connect (Android) to scan the device's characteristics.
> You can also send data using this app, that's how i found out the dataformats.

Is the app available as an apk file?

**Comment by pledi** [comment]
> 
> 
> > I used nRF Connect (Android) to scan the device's characteristics.
> > You can also send data using this app, that's how i found out the dataformats.
> 
> Is the app available as an apk file?

havnt found it on apkmirror, but you can[ pull it from your own device](https://stackoverflow.com/a/18003462).
For decompiling the application we could use apktool for example. 
Althought since this repo already sums up what the device sends, the only interesting thing we could grab would be the pairing process..

In general, we could follow [this guide](https://reverse-engineering-ble-devices.readthedocs.io/en/latest/protocol_reveng/00_protocol_reveng.html#logging-via-android) to take a look at the interesting code parts. 
I'm soon done with my thesis, then I will give it a try.

**Comment by pledi** [comment]
I've had some free time and used it to learn Qt and created [EmberControl](https://github.com/pledi/EmberControl), a GUI for communicating with the Ember Mug. 
It's very work in progress, but feel free to check it out. 
Currently, I'm having problems setting the target temperature of the mug. It seems to set something, since I can fetch it again afterwards, but the mug is not heating to get to the temperature.

**Comment by Ryamonster10** [comment]
Nice! I am getting an error when running it though...
"
  File "main.py", line 46
    async def getCurrentTemp(self):
        ^
SyntaxError: invalid syntax
" 
Don't know what it means but maybe you do.

**Comment by pledi** [comment]
Open a issue on the repo, I still need to write a "how to run" option and will include such cases.
